# Generated by Django 3.2.6 on 2023-03-18 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('course_id', models.SlugField(blank=True, default=0, max_length=10, null=True)),
                ('course_type', models.CharField(blank=True, max_length=50, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=5000)),
                ('dp', models.ImageField(blank=True, default='media/course.png', null=True, upload_to='courses/')),
                ('next_start_date', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePreRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('learner_id', models.SlugField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(max_length=500)),
                ('province_state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('vat', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course_reg.course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('learner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner', to='course_reg.learner')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='benefits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='course_reg.coursebenefit'),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisites', to='course_reg.courseprerequisite'),
        ),
    ]
