# Generated by Django 3.2.6 on 2023-03-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pre_requisites',
        ),
        migrations.AddField(
            model_name='coursebenefit',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='course_reg.course'),
        ),
        migrations.AddField(
            model_name='courseprerequisite',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisites', to='course_reg.course'),
        ),
    ]
