# Generated by Django 3.2.6 on 2023-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='vat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learner',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
