# Generated by Django 3.2.6 on 2023-03-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reg', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
