# Generated by Django 3.2.6 on 2023-03-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reg', '0004_learner_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
